project_1/blog_posts/forms.py
################################################################################
#########################   Setting up forms for posts  ########################
################################################################################

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired
from flask_ckeditor import CKEditorField

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    #text = TextAreaField('Text', validators=[DataRequired()])
    text = CKEditorField('Text', validators=[DataRequired()])
    submit = SubmitField('Post')

project_1/blog_posts/views.py
################################################################################
#######################    Setting up views for posts    #######################
################################################################################

# imports
from flask import render_template, url_for, flash, request, redirect, Blueprint
from flask_login import current_user, login_required
from project_1 import db
from project_1.models import BlogPost
from project_1.blog_posts.forms import BlogPostForm

blog_posts = Blueprint('blog_posts',__name__)

# We want views for (CRUD)
#   1. CREATE a blogpost
#   2. Viewing a blogpost
#   3. Updating a blogpost
#   4. Deleting a blogpost

# create
@blog_posts.route('/create',methods=['GET','POST'])
@login_required
def create_post():
    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post = BlogPost(title=form.title.data,
                                text=form.text.data,
                                user_id=current_user.id)

        db.session.add(blog_post)
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('core.index'))

    return render_template('create_post.html', form=form)

# view
@blog_posts.route('/<int:blog_post_id>')
def blog_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    return render_template('blog_post.html', title=blog_post.title,
                            date=blog_post.date, post=blog_post)

# update
# Here we check if the user visiting is actually the author,
# if not, they are not able to update.
# Then we reset the title and text to the title and text in the update form
# and eventually we commit those changes to the db
@blog_posts.route('/<int:blog_post_id>/update', methods=['GET','POST'])
@login_required
def update(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)

    if blog_post.author != current_user:
        abort(403)

    form = BlogPostForm()

    if form.validate_on_submit():

        blog_post.title = form.title.data
        blog_post.text = form.text.data
        db.session.commit()
        flash('Blog Post Created')
        return redirect(url_for('blog_posts.blog_post', blog_post_id=blog_post.id))

    elif request.method == 'GET':
        form.title.data = blog_post.title
        form.text.data = blog_post.text

    return render_template('create_post.html', title='Updating', form=form)

# delete
@blog_posts.route("/<int:blog_post_id>/delete", methods=['POST'])
@login_required
def delete_post(blog_post_id):
    blog_post = BlogPost.query.get_or_404(blog_post_id)
    if blog_post.author != current_user:
        abort(403)
    db.session.delete(blog_post)
    db.session.commit()
    flash('Post has been deleted')
    return redirect(url_for('core.index'))

project_1/core/views.py
from project_1.models import BlogPost
from flask import render_template, request, Blueprint, session
import numpy as np
import pandas as pd

core = Blueprint('core',__name__)

df = pd.DataFrame({'column 1 ': [4, 6, 1, 3, 7],
                   'column 2 ': [5, 6, 7, 8, 9],
                   'column 3 ': [5, 6, 7, 8, 9],
                   'column 4 ': [5, 6, 7, 8, 9],
                   'column 5 ': [5, 6, 7, 8, 9],
                   'column 6 ': [5, 6, 7, 8, 9],
                   'column 7 ': [5, 6, 7, 8, 9],
                   'column 8 ': [5, 6, 7, 8, 9],
                   'column 9 ': [5, 6, 7, 8, 9],
                   'column 10 ': [5, 6, 7, 8, 9],
                   'column 11 ': ['a', 'b', 'c', 'd', 'e']})

@core.route('/')
def index():
    page = request.args.get('page',1,type=int)
    blog_posts = BlogPost.query.order_by(BlogPost.date.desc()).paginate(page=page, per_page=10)
    return render_template('index.html', blog_posts=blog_posts)

@core.route('/info')
def info():
    return render_template('info.html')

@core.route('/contact')
def contact():
    return render_template('contact.html')

@core.route('/cases')
def cases():
    return render_template('cases/cases.html',  tables=[df.to_html(classes='data')], titles=df.columns.values)

project_1/users/views.py
################################################################################
# We need to create the views for:
#   1. Register a user
#   2. Login a user
#   3. Logout a user
#   4. Show an account
#   5. Users list of posts (væg)
#
# Therefore, we have to make a few imports in regard to templates, redirections
# blueprints, user functionality, database interaction, models, forms and picture
################################################################################
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from project_1 import db
from project_1.models import User, BlogPost
from project_1.users.forms import RegistrationForm, LoginForm, UpdateUserForm
from project_1.users.picture_handler import add_profile_pic

# First we will register this as a blueprint
users = Blueprint('users',__name__)

################################################################################
#   1. Registration view
# We link it to registrationform, and say, if it validates on submit we create
# a user object based on the elements we acquire at form.column.data
# in the db.session we add and commit it to our database, and redirects the user
# to the login page. But if we do not return render template at the end,
# we wont have a view for the registration page itself
@users.route('/register',methods=['GET','POST'])
def register():
    form = RegistrationForm()

    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    password=form.password.data)

        db.session.add(user)
        db.session.commit()
        flash('Your user has been created')
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


################################################################################
#   2. Login view
# As opposed to the registration view, we do not want to create, we just want to
# query, and check if the user already has a spot in our database
# Upon logging in, they provide an email address, and we are filtering by that mail.
# Often a usear are searching for something is prompted to login,
# there we have our next object to
@users.route('/login', methods=['GET','POST'])
def login():

    form = LoginForm()
    if form.validate_on_submit():

        user = User.query.filter_by(email=form.email.data).first()

        if user.validate_password(form.password.data) and user is not None:

            login_user(user)
            flash('You are now logged in')

            next = request.args.get('next')

            if next == None or not next[0]=='/':
                next = url_for('core.index')
            return redirect(next)

    return render_template('login.html',form=form)


################################################################################
#   3. Logout view
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('core.index'))


################################################################################
#   4. Account
# First, you need to be logged in, to edit the profile
# If people actually submittet something to the picture filefield in forms,
# then the if form.picture.data: gets activated. The if statement, grabs the UserName
# and pass that in to the add_profile_pic function we defined in picture_handler.py.
# Then we take the attribute profile_image, specified in models.py and say its now equal to pic
@users.route('/account', methods=['GET','POST'])
@login_required
def account():

    form = UpdateUserForm()
    if form.validate_on_submit():

        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data, username)
            current_user.profile_image = pic

        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.about_author = form.about_author.data
        db.session.commit()
        flash('Your account has been updated')
        return redirect(url_for('users.account'))

    elif request.method =='GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.about_author.data = current_user.about_author

    profile_image = url_for('static', filename='profile_pics/'+current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

################################################################################
#   5. Wall / user post view
# When you go to your website/username, we will pass the username,
# grab the page, using the page variable, that will allow us to cycle through pages.
# Then we will query for that user. Here we use the method .first_or_404 to ensure
# that they will get redirected to our 404 if they type it out wrong.
# Once we have the user, we will grab the blog post, created in models and say
# author = user (our foreign key relationship specified in models).
# Then we will order it by blogpost date in decending order.
# Then we call the paginate function to ensure that we get actual pages
# eventually we return the html page using render_template
@users.route("/<username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.date.desc()).paginate(page=page, per_page=5)
    return render_template('user_blog_posts.html', blog_posts=blog_posts, user=user)

project_1/templates/account.html
{% extends 'base.html' %}
{% block content %}

  <section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Profile settings</h1>
      <p class="lead text-muted">{{current_user.username}}</p>
      <p>
        <img align = 'center' src="{{url_for('static', filename='profile_pics/'+current_user.profile_image)}}" alt="">
      </p>
    </div>
      <form method= 'POST' action='' enctype='multipart/form-data'>
        <h1 class="h3 mb-3 fw-normal">Edit your profile</h1>
        {{form.hidden_tag()}}
        <div align = "left" class="form-group">
          {{form.username.label(class = 'form-group')}}
          {{form.username(class="form-control")}}
        </div>
        <br>
        <div align = "left" class="form-group">
          {{form.email.label(class = 'form-group')}}
          {{form.email(class="form-control")}}
        </div>
        <br>
        <div align = "left" class="form-group">
          {{form.about_author.label(class = 'form-group')}}
          {{form.about_author(class="form-control")}}
        </div>
        <br>
        <div align = "left" class="form-group">
          {{form.picture.label(class = 'form-group')}}
          {{form.picture(class="form-control")}}
        </div>
        <br>
        <div class='form-group'>
        {{form.submit(class = 'btn btn-primary btn-lg')}}
        </div>
      </form>

    </div>
  </section>
{% endblock %}

project_1/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <title>PNConsulting</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&family=Oswald:wght@300;400&family=Roboto+Condensed:ital,wght@1,700&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <style>
      body {
      font-family: 'Lato', sans-serif;
      font-family: 'Oswald', sans-serif;
      }

    </style>

  </head>
  <body>

    <header class = "header1">


    <nav >
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #303030; height: 100px ">

    <!-- Navbar content -->
    <div class="container">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px;" aria-current="page" href="{{ url_for('core.index')}}">HOME</a>
        </li>
        <br>
        <li id = "testid" class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{ url_for('core.info')}}">ABOUT</a>
        </li>
      <br>
        <li id = "testid" class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{ url_for('core.contact')}}">CONTACT</a>
        </li>
        <br>
        {% if current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{url_for('users.logout')}}">LOG OUT</a>
        </li>
        <br>
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{url_for('users.user_posts', username=current_user.username)}}">PROFILE</a>
        </li>
        <br>
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{url_for('blog_posts.create_post')}}">POST CONTENT</a>
        </li>
        <br>
        {% else %}
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{url_for('users.login')}}">LOG IN</a>
        </li>
        <br>
        <li class="nav-item">
          <a class="nav-link active" style = "letter-spacing: 1.7px; text-indent: 35px" href="{{url_for('users.register')}}">REGISTER</a>
        </li>
        <br>
        <li class="nav-item dropdown">
      <!-- NOTE:      <a class="nav-link dropdown-toggle" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Yet to be launched" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="true">Products</a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul> -->
        </li>
        {% endif %}
      </ul>
      <form>
        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      </form>
    </div>
    </div>
    </nav>
    </nav>
    </header>



<div class="container-fluid">

<main>


    {% block content %}
    {% endblock %}

  </div>

</main>
  </body>
  <footer class=" container-flex py-5 bg-dark">
      <div class="container">
    <div class="row">
      <div class="col-2 container">
        <ul class="nav flex-column">
          <li class="nav-item mb-2"><a href="{{ url_for('core.contact')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Contact</a></li>
          <li class="nav-item mb-2"><a href="{{ url_for('core.info')}}" class="nav-link p-0" style="color:white; opacity:0.95;">About</a></li>
          {% if current_user.is_authenticated %}
          <li class="nav-item mb-2"><a href="{{url_for('users.account')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Account</a></li>
          <li class="nav-item mb-2"><a href="{{url_for('blog_posts.create_post')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Create post</a></li>
          <li class="nav-item mb-2"><a href="{{url_for('users.logout')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Logout</a></li>
          {% else %}
          <li class="nav-item mb-2"><a href="{{url_for('users.login')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Login</a></li>
          <li class="nav-item mb-2"><a href="{{url_for('users.register')}}" class="nav-link p-0" style="color:white; opacity:0.95;">Register</a></li>
          {% endif %}
        </ul>
      </div>
        <div class="col-9 offset-1">
          <form>
            <h5 style="color:white; opacity:0.95;">Subscribe to our newsletter</h5>
            <p style="color:white; opacity:0.95;">Monthly digest of whats new and exciting from us. </p>
            <div class="d-flex w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <button class="btn btn-md btn-outline-dark" type="button">Subscribe</button>
            </div>
          </form>
        </div>
      </div>
      </div>
      </div>


    </footer>
</html>

project_1/templates/blog_post.html
{% extends 'base.html' %}
{% block content %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
        <h2>{{ post.title|upper }}</h2>
        <h3 class="lead text-muted">Written by: {{post.author.username}}</h3>
        <p class="lead text-muted">Published: {{post.date.strftime('%d %B %Y')}}</p>
    </div>
  </div>
</section>
<div class="py-5 text container">
    <div class="row py-lg-5">
      <div style="opacity:0.85;" class="col-lg-6 col-md-8 mx-auto">
        <p>{{post.text|safe}}</p>
      </div>
    </div>
</div>
{% if post.author == current_user %}
<div class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <a class="btn btn-md btn-outline-dark" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Update</a>
       <button type="button" class="btn btn-md btn-outline-dark" data-bs-toggle="modal" data-bs-target="#del_modal">Delete</button>
     </div>
    </div>
    </div>
    {% endif %}




<!-- Modal for Pop Up-->
  {# https://getbootstrap.com/docs/4.1/components/modal/ #}
  {# Notice how the link with the id to the button above! #}
  <div class="modal" tabindex="-1" role="dialog" id="del_modal">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Delete Post Pop up Modal</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Are you sure you want to delete this blog post?</p>
        </div>
        <div class="modal-footer">
          <button action="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>

          <form action="{{ url_for('blog_posts.delete_post', blog_post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

project_1/templates/index.html
{% extends 'base.html' %}
{% block content %}



<link rel="stylesheet" href="static\index.css">

<div class="container">




<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://lh3.googleusercontent.com/kF0INXBwNymjHlTtFI4spCvOIeV6OO-8PBl_kp7R4J4IXfpXHEn_Vp7lku0WAxa9ERW2mp9mac9hfLyJsSOi9La-NVKPLeuA0LbjrEtOf4-Dim-_96ND7JdzPvL7Efh6zzX1-EHoRA=w2400" class="d-block w-100" alt="...">
      <div class="carousel-caption gradient-background text-start">
        <h1 style = "letter-spacing: 1.7px;">ABOUT</h1>
        <p>Learn more about this page</p>
        <p><a class="btn btn-md btn-outline-dark" href="{{ url_for('core.info')}}">Read more</a></p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://lh3.googleusercontent.com/4kmQDMSxMwBQhqGgSEXbHxqqYry_uEO77AK6-jvw3BKPWXCe9Bz4bMAFLHcIS94pOXic1NyuLpK6qabhDbKBjM8vH0MzD_OfWTJXnPeASIpnRoZnbLWOI35oRE-KrHTBlOSxAuNPNg=w2400" class="d-block w-100" alt="...">
      <div class="carousel-caption text">
        <h1 style = "letter-spacing: 1.7px;">CONTACT</h1>
        <p>Get in contact with its creator</p>
        <p><a class="btn btn-md btn-outline-dark" href="{{ url_for('core.contact')}}">Read more</a></p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://lh3.googleusercontent.com/rnijMtwU2aACek7sF6yPE5Wc5XGg-XR19t0_k5e3tulxr9r1nSKVkaU5iaawU-l9nuO7ARiqC3MAGWsLr5F9Fcosra8teolmvboxic8X-R3sZ8jA4nX-SwYtyJb5wr5qmAexGnVQpg=w2400" class="d-block w-100" alt="...">
      <div class="carousel-caption text-end">
        <h1 style = "letter-spacing: 1.7px;">CONTRIBUTE</h1>
        <p>Start writing blog posts today</p>
        <p><a class="btn btn-md btn-outline-dark" href="{{url_for('users.login')}}">Read more</a></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

<div class="container">
  <br>
  <br>
  <br>
  <h3 class="text-center" style = "letter-spacing: 1.7px;">BLOGPOSTS</h3>
  <br>
  <h2 class="border-bottom"></h2>
  <br>
<div class="grid_1">





{% for post in blog_posts.items %}
  <div class="album py-5 light">

    <div class="container">


      <!-- NOTE:    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3"> -->

          <div class="col">
            <div class="card-group">
            <div class="card shadow-sm">
              <a href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">
              <img align='center' src="{{ url_for('static', filename='profile_pics/' + post.author.profile_image) }}" height = "100%" width="100%">
              </a>
              <div class="card-body">
                <h5 style = "letter-spacing: 1.7px;">{{ post.title|upper }}</h5> <br>
                <p><a class = 'text-muted' href="{{ url_for('users.user_posts', username=post.author.username) }}">By: {{ post.author.username }}</a> </p> <br>
                <div class="d-flex justify-content-between align-items-center">
                  <div class="btn-group">
                    <a class="btn btn-sm btn-outline-dark" href="  {{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}">View article</a>
                  </div>
                  <small class="text-muted">{{post.date.strftime('%d, %B, %Y')}}</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
        </div>
    <!-- NOTE:  </div> -->
    {% endfor %}
    </div>
</div>
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
          {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if blog_posts.page == page_num %}
            <li class ='page-item disabled'>
              <a class='page-link' href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
            </li>
            {% else %}
            <li class ='page-item'>
              <a class='page-link' href="{{url_for('core.index', page=page_num)}}">{{page_num}}</a>
            </li>
            {% endif %}
          {% endfor %}
        </ul>
      </nav>

{% endblock %}

project_1/templates/user_blog_posts.html
{% extends 'base.html' %}
{% block content %}

<div class="container">

<div class="card">
  <div class="card-head">
    <div class="py-5 text container">
      <img align='right' src="{{ url_for('static', filename='profile_pics/' + user.profile_image) }}">
      <h4 align='left'>{{user.username}}</h4>
      <br>
      <p align='left'><b>Mail: </b>{{user.email}}</p>
      <br>
      <h6><b>About: </b></h6>
      <div class="col-md-5">
      <p>{{user.about_author}}</p>
      </div>
      <br>

      {% if user == current_user %}
        <a class="btn btn-md btn-outline-dark" href="{{url_for('users.account')}}">Edit information</a>
        <a class="btn btn-md btn-outline-dark" href="{{url_for('blog_posts.create_post')}}">Create post</a>
        {% endif %}
      </div>
    </div>
    </div>
    </div>


<br>
<br>

<div class="container">



    <div class="row g-5">
        <div class="col-md-8">
            <h4>BLOGPOSTS</h4>
            <h2 class="border-bottom"></h2>

          {% for post in blog_posts.items %}
          <br>
          <article class="blog-post">
            <h3><a href="{{ url_for('blog_posts.blog_post', blog_post_id=post.id) }}" style="color: black">{{ post.title }}</a></h3>
            <p><a href="{{ url_for('users.user_posts', username=post.author.username) }}" style="color: black">By: {{ post.author.username }}</a>
            <p class="text-muted">Published on: {{ post.date.strftime('%Y-%m-%d') }}</p>
            <p>{{post.text|safe }}</p>

            {% if user == current_user %}
              <a class="btn btn-sm btn-outline-dark" href="{{ url_for('blog_posts.update', blog_post_id=post.id) }}">Edit post</a>
              <br>
              <br>
              <br>
              <br>
              {% endif %}
              <h2 class="border-bottom"></h2>
          </article>
          {% endfor %}

        </div>


      </div>
      </div>



<br>
<br>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
      {% for page_num in blog_posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if blog_posts.page == page_num %}
        <li class ='page-item disabled'>
          <a class='page-link' href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li>
        {% else %}
        <li class ='page-item'>
          <a class='page-link' href="{{url_for('users.user_posts', username=user.username, page=page_num)}}">{{page_num}}</a>
        </li>
        {% endif %}
      {% endfor %}
    </ul>
  </nav>


{% endblock %}